const t = (l, f) => { try { console.log(l, "->", String(f())); } catch (e) { console.log(l, "THREW", e.constructor.name); } };
t("accessor to data non-config", () => { const o={}; Object.defineProperty(o,"x",{get(){return 1}}); return Object.defineProperty(o,"x",{value:2}); });
t("data to accessor non-config", () => { const o={}; Object.defineProperty(o,"x",{value:1}); return Object.defineProperty(o,"x",{get(){return 2}}); });
t("change enumerable non-config", () => { const o={}; Object.defineProperty(o,"x",{value:1}); return Object.defineProperty(o,"x",{enumerable:true}); });
t("same enumerable ok", () => { const o={}; Object.defineProperty(o,"x",{value:1}); Object.defineProperty(o,"x",{enumerable:false}); return o.x; });
t("writable true->false ok", () => { const o={}; Object.defineProperty(o,"x",{value:1,writable:true}); Object.defineProperty(o,"x",{writable:false}); return o.x; });
t("non-extensible add", () => { const o=Object.preventExtensions({}); return Object.defineProperty(o,"x",{value:1}); });
t("non-extensible existing ok", () => { const o={x:1}; Object.preventExtensions(o); Object.defineProperty(o,"x",{value:2}); return o.x; });
t("frozen redefine", () => { const o=Object.freeze({x:1}); return Object.defineProperty(o,"x",{value:2}); });
t("sealed add", () => { const o=Object.seal({}); return Object.defineProperty(o,"x",{value:1}); });
t("sealed modify value ok", () => { const o=Object.seal({x:1}); Object.defineProperty(o,"x",{value:2}); return o.x; });
t("partial descriptor keeps getter", () => { const o={}; Object.defineProperty(o,"x",{get(){return 7},configurable:true}); Object.defineProperty(o,"x",{enumerable:true}); return o.x; });
t("new prop defaults are false", () => { const o={}; Object.defineProperty(o,"x",{value:1}); const d=Object.getOwnPropertyDescriptor(o,"x"); return [d.value,d.writable,d.enumerable,d.configurable].join(","); });
t("value omitted on new prop is undefined", () => { const o={}; Object.defineProperty(o,"x",{enumerable:true}); return "x" in o ? String(o.x) : "missing"; });
t("configurable allows kind change", () => { const o={}; Object.defineProperty(o,"x",{value:1,configurable:true}); Object.defineProperty(o,"x",{get(){return 9}}); return o.x; });
t("redefine keeps attributes", () => { const o={}; Object.defineProperty(o,"foo",{value:1}); Object.defineProperty(o,"foo",{value:1}); const d=Object.getOwnPropertyDescriptor(o,"foo"); return [d.writable,d.enumerable,d.configurable].join(","); });
t("array index accessor attributes", () => { const a=[]; const s=function(v){}; Object.defineProperty(a,"0",{set:s}); Object.defineProperty(a,"0",{set:s}); const d=Object.getOwnPropertyDescriptor(a,"0"); return [d.enumerable,d.configurable,d.set===s].join(","); });
t("inherited descriptor field is seen", () => { const o={}; Boolean.prototype.enumerable = true; Object.defineProperty(o,"p",new Boolean(true)); delete Boolean.prototype.enumerable; return Object.keys(o).join(","); });
t("delete a static method", () => { class C { static m(){} } const had = Object.prototype.hasOwnProperty.call(C,"m"); const r = delete C.m; return [had, r, Object.prototype.hasOwnProperty.call(C,"m")].join(","); });
t("delete a function property", () => { function f(){} f.x=1; delete f.x; return Object.prototype.hasOwnProperty.call(f,"x"); });
t("delete a function name", () => { function f(a){} delete f.name; return Object.prototype.hasOwnProperty.call(f,"name"); });
