#ifndef MILOJS_H
#define MILOJS_H

#include "libmilojs.h"

enum milojs_status {
    MILOJS_STATUS_OK = 0,
    MILOJS_STATUS_INVALID_ARGUMENT = -1,
    MILOJS_STATUS_BUSY = -2,
    MILOJS_STATUS_INVALID_CONTEXT = -3,
    MILOJS_STATUS_JS_EXCEPTION = -4,
    MILOJS_STATUS_WRONG_TYPE = -5,
    MILOJS_STATUS_INIT_FAILED = -6,
};

enum milojs_value_kind {
    MILOJS_VALUE_UNDEFINED = 0,
    MILOJS_VALUE_NULL = 1,
    MILOJS_VALUE_BOOL = 2,
    MILOJS_VALUE_NUMBER = 3,
    MILOJS_VALUE_STRING = 4,
    MILOJS_VALUE_OBJECT = 5,
    MILOJS_VALUE_FUNCTION = 6,
    MILOJS_VALUE_BIGINT = 7,
};

#endif
