# Random programs for tools/fuzz.sh (crash shapes vs node) and
# tools/vm-differential.sh (compiled path vs tree-walking evaluator).
#
# The differential only sees what this emits, so operators applied to awkward
# operands go INSIDE a function body or a loop: those are the only places
# src/engine/bytecode.milo compiles, and an opcode that disagrees with the
# evaluator is invisible anywhere else. Generating `-Symbol()` at top level, as
# this did, could never have caught the Op.Neg bug that shipped.
import random, sys
MATRIX = len(sys.argv) > 1 and sys.argv[1] == "--matrix"
seed = 0 if MATRIX else int(sys.argv[1])
random.seed(seed)
V = ["a","b","c","o","arr","f","m","s"]
def val(d=0):
    if d > 2: return random.choice(["1","'x'","null","true","undefined"])
    return random.choice([
        "1","0","-1","'str'","null","undefined","true","NaN",
        "[%s]" % ",".join(val(d+1) for _ in range(random.randint(0,3))),
        "{%s}" % ",".join("k%d:%s" % (i,val(d+1)) for i in range(random.randint(0,3))),
        "new Map([['k',%s]])" % val(d+1),
        "new Set([%s])" % val(d+1),
        "(function(){return %s;})" % val(d+1),
        "Symbol('s')","new Date(0)","/re/g","new Int32Array([1,2])",
        "(()=>%s)" % val(d+1),
    ])
UNOPS = ["-", "+", "~", "!", "void "]
BINOPS = ["+", "-", "*", "/", "%", "<", ">", "<=", "==", "===", "&", "|", "^", "<<", ">>", "**"]

# Operands chosen to make a compiled fast path and the evaluator disagree if they
# can: values whose coercion throws, values with two representations, and values
# the fast path is most likely to have assumed away. Drawn from here rather than
# from val() because val() reaches a Symbol about one time in sixteen, and the
# operator, the operand and the function wrapper all have to line up at once --
# the Op.Neg bug needed `-Symbol()` inside a function body, which is a 0.1% event
# per statement that way and never fired in 150 seeds.
AWKWARD = [
    "Symbol('s')", "10n", "-0", "NaN", "Infinity", "-Infinity",
    "null", "undefined", "''", "'0'", "'1e400'", "[]", "[1]", "({})",
    "({valueOf(){ throw new TypeError('x'); }})",
    "({valueOf(){ return 2; }})", "({toString(){ return '3'; }})",
    "({[Symbol.toPrimitive](){ return 4; }})",
    "new Int32Array([1,2])", "new Proxy({k0:1}, {})",
    "Object('s')", "new Number(5)", "true", "0.1", "2**53",
]

def awkward():
    return random.choice(AWKWARD)

def fnop():
    """An operator applied inside a function body, which is what the VM compiles."""
    a, b = awkward(), awkward()
    return random.choice([
        "try { (function(x){ return %s x; })(%s); } catch(e) {}" % (random.choice(UNOPS), a),
        "try { (function(x,y){ return x %s y; })(%s, %s); } catch(e) {}" % (random.choice(BINOPS), a, b),
        "try { (function(x){ return x.k0; })(%s); } catch(e) {}" % a,
        "try { (function(x){ x.k0 = %s; return x; })(Object(%s)); } catch(e) {}" % (b, a),
        "try { (function(x){ return {p: x, q: %s}; })(%s); } catch(e) {}" % (b, a),
        "try { (function(x){ var t = 0; for (var i=0;i<3;i++) t = t %s x; return t; })(%s); } catch(e) {}"
            % (random.choice(BINOPS), a),
        "try { (function(x){ return x[%s]; })(%s); } catch(e) {}" % (b, a),
    ])

def stmt(d=0):
    v = random.choice(V)
    return random.choice([
        fnop(), fnop(),
        "var %s = %s;" % (v, val()),
        "%s = %s;" % (v, val()),
        "try { %s } catch(e) {}" % stmt(d+1) if d < 2 else "void 0;",
        "for (var i=0;i<3;i++) { %s }" % (stmt(d+1) if d < 2 else "void 0;"),
        "if (%s) { %s }" % (val(), stmt(d+1) if d < 2 else "void 0;"),
        "(function(){ %s })();" % (stmt(d+1) if d < 2 else "void 0;"),
        "[%s].forEach(function(x){ %s });" % (val(), stmt(d+1) if d < 2 else "void 0;"),
        "%s = [%s].map(function(x){ return x; });" % (v, val()),
        "JSON.stringify(%s);" % val(),
        "String(%s);" % val(),
        "Object.keys(Object(%s));" % val(),
        "(%s).toString();" % val(),
        "delete %s.k0;" % v,
        "%s = Object.assign({}, {q:%s});" % (v, val()),
        "function* g(){ yield %s; } [...g()];" % val(),
        "%s = structuredClone({z:%s});" % (v, val()),
    ])
# `--matrix` emits the operator x operand cross product instead of a random
# program: every unary and binary operator applied to every awkward operand,
# inside a function body so the compiler sees it. Random seeds give breadth, but
# the class this is meant to catch is small and enumerable, and leaving it to
# chance means a 1-in-24 operand draw has to coincide with a 1-in-5 operator draw.
# It did not fire in 120 seeds while the Op.Neg bug was reintroduced.
if MATRIX:
    print("// generated by tools/fuzz-gen.py --matrix")
    print("function u(f, x) { try { return String(f(x)); } catch (e) { return 'ERR:' + e.constructor.name; } }")
    print("function b2(f, x, y) { try { return String(f(x, y)); } catch (e) { return 'ERR:' + e.constructor.name; } }")
    n = 0
    for op in UNOPS:
        for a in AWKWARD:
            print("console.log(%d, u(function(x){ return %s x; }, %s));" % (n, op, a))
            n += 1
    for op in BINOPS:
        for a in AWKWARD:
            print("console.log(%d, b2(function(x, y){ return x %s y; }, %s, 2));" % (n, op, a))
            n += 1
            print("console.log(%d, b2(function(x, y){ return x %s y; }, 2, %s));" % (n, op, a))
            n += 1
    for a in AWKWARD:
        print("console.log(%d, u(function(x){ return x.k0; }, %s));" % (n, a)); n += 1
        print("console.log(%d, u(function(x){ x.k0 = 1; return x.k0; }, %s));" % (n, a)); n += 1
        print("console.log(%d, u(function(x){ return {p: x}.p; }, %s));" % (n, a)); n += 1
        print("console.log(%d, u(function(x){ var t = 0; for (var i = 0; i < 3; i++) t = t + x; return t; }, %s));" % (n, a)); n += 1
    sys.exit(0)

print("var a,b,c,o,arr,f,m,s;")
for _ in range(random.randint(5, 25)):
    print(stmt())
print("console.log('FUZZ_OK');")
