#!/usr/bin/env node
// Generates src/unicase.milo — the Unicode case-mapping tables for
// String.prototype.toUpperCase/toLowerCase.
//
// node is the oracle here as everywhere else in this repo: the tables are read
// out of the host's own ICU by asking it to case-map every code point, so the
// generated engine agrees with node by construction rather than by transcribing
// UnicodeData.txt by hand. Re-run after a node upgrade if a case mapping changes.
//
//   node tools/gen-unicase.mjs > src/unicase.milo
//   node tools/gen-unicase.mjs --check      # fail if src/unicase.milo has drifted
//
// The header says "do not edit by hand", which was a request until --check existed.
// A generated file with no regeneration gate is a generated file that quietly
// stops matching its generator — and this one is a correctness table, so drift
// means the engine case-maps differently from the node it was derived from.
//
// Emitted as balanced if-trees rather than data tables: milo has no static
// array initialiser, and a tree of comparisons is O(log n) per character with
// no allocation and no lazily-built global to keep in sync.

const MAX = 0x110000;

function collect(kind) {
  const single = [], multi = [];
  for (let c = 0; c < MAX; c++) {
    if (c >= 0xd800 && c <= 0xdfff) continue;
    const s = String.fromCodePoint(c);
    const t = kind === "u" ? s.toUpperCase() : s.toLowerCase();
    if (t === s) continue;
    const a = [...t];
    if (a.length === 1) single.push([c, a[0].codePointAt(0) - c]);
    else multi.push([c, t]);
  }
  return { single, multi };
}

// consecutive code points sharing one delta collapse to a run; the Latin/Greek
// even-odd alternation collapses further to a stride-2 run
function ranges(single) {
  const r = [];
  let i = 0;
  while (i < single.length) {
    let j = i;
    while (j + 1 < single.length && single[j + 1][0] === single[j][0] + 1 && single[j + 1][1] === single[i][1]) j++;
    r.push([single[i][0], single[j][0], 1, single[i][1]]);
    i = j + 1;
  }
  const out = [];
  let k = 0;
  while (k < r.length) {
    let m = k;
    while (m + 1 < r.length && r[m + 1][0] === r[m][0] + 2 && r[m][0] === r[m][1] &&
           r[m + 1][0] === r[m + 1][1] && r[m + 1][3] === r[k][3]) m++;
    if (m > k) out.push([r[k][0], r[m][0], 2, r[k][3]]);
    else out.push(r[k]);
    k = m + 1;
  }
  return out;
}

const hex = (n) => "0x" + n.toString(16).toUpperCase();
const add = (delta) => (delta >= 0 ? `v + ${delta}` : `v - ${-delta}`);

// balanced if-tree over sorted ranges: pick the middle, recurse on both halves
function tree(rs, ind) {
  const p = "    ".repeat(ind);
  if (rs.length === 0) return `${p}return cp\n`;
  if (rs.length === 1) {
    const [lo, hi, step, d] = rs[0];
    if (lo === hi) return `${p}if v == ${hex(lo)} {\n${p}    return (${add(d)}) as i32\n${p}}\n${p}return cp\n`;
    const parity = step === 2 ? ` && (v - ${hex(lo)}) % 2 == 0` : "";
    return `${p}if v >= ${hex(lo)} && v <= ${hex(hi)}${parity} {\n${p}    return (${add(d)}) as i32\n${p}}\n${p}return cp\n`;
  }
  const mid = rs.length >> 1;
  const [lo, hi, step, d] = rs[mid];
  const parity = step === 2 ? ` && (v - ${hex(lo)}) % 2 == 0` : "";
  let out = `${p}if v < ${hex(lo)} {\n`;
  out += tree(rs.slice(0, mid), ind + 1);
  out += `${p}}\n${p}if v > ${hex(hi)} {\n`;
  out += tree(rs.slice(mid + 1), ind + 1);
  out += `${p}}\n${p}if v >= ${hex(lo)}${parity} {\n${p}    return (${add(d)}) as i32\n${p}}\n${p}return cp\n`;
  return out;
}

function multiTree(ms, ind) {
  const p = "    ".repeat(ind);
  if (ms.length === 0) return `${p}return ""\n`;
  const mid = ms.length >> 1;
  const [cp, str] = ms[mid];
  const lit = JSON.stringify(str);
  let out = `${p}if v < ${hex(cp)} {\n`;
  out += multiTree(ms.slice(0, mid), ind + 1);
  out += `${p}}\n${p}if v > ${hex(cp)} {\n`;
  out += multiTree(ms.slice(mid + 1), ind + 1);
  out += `${p}}\n${p}return ${lit}\n`;
  return out;
}

const up = collect("u"), lo = collect("l");
const upR = ranges(up.single), loR = ranges(lo.single);

let out = `// GENERATED by tools/gen-unicase.mjs — do not edit by hand.
//
// Unicode case mapping for String.prototype.toUpperCase/toLowerCase. Before
// this file both were ASCII-plus-Latin-1 only, so "привет".toUpperCase() and
// "αβγ".toUpperCase() answered themselves unchanged — every non-Latin script
// silently passed through.
//
// The single-code-point mappings are ${upR.length} upper / ${loR.length} lower ranges,
// searched as a balanced if-tree. The ${up.multi.length} upper mappings that GROW
// (ß -> SS, ﬁ -> FI, the Greek iota-subscript family) cannot be expressed as a
// code point delta and live in upperSpecial/lowerSpecial, which answer "" when
// the character has no expansion.

// Simple (one code point in, one out) uppercase mapping.
pub fn upperCp1(cp: i32): i32 {
    let v = cp as i64
${tree(upR, 1)}}

// Simple lowercase mapping.
pub fn lowerCp1(cp: i32): i32 {
    let v = cp as i64
${tree(loR, 1)}}

// Uppercase mappings that expand to more than one code point. "" means none.
pub fn upperSpecial(cp: i32): string {
    let v = cp as i64
${multiTree(up.multi, 1)}}

// Lowercase mappings that expand to more than one code point. "" means none.
pub fn lowerSpecial(cp: i32): string {
    let v = cp as i64
${multiTree(lo.multi, 1)}}
`;
if (process.argv.includes("--check")) {
  const { readFileSync } = await import("node:fs");
  const target = new URL("../src/unicase.milo", import.meta.url);
  const have = readFileSync(target, "utf8");
  if (have !== out) {
    console.error("gen-unicase: src/unicase.milo does not match its generator.");
    console.error("Regenerate with: node tools/gen-unicase.mjs > src/unicase.milo");
    console.error("(If node's ICU changed under you, read the diff before committing it —");
    console.error(" it moves what the engine believes about Unicode case mapping.)");
    process.exit(1);
  }
  console.log("gen-unicase: src/unicase.milo matches its generator");
} else {
  process.stdout.write(out);
}
